name: CI

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '*.yaml'
  schedule:
    - cron: '0 9 7 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        file:
          - tagtuner-XIAO-custom
          - tagtuner-D1-custom1
          - tagtuner-atom-grove-ble
          - tagtuner-for-tagreader
          - tagtuner-on-ha-voice
        esphome-version:
          - stable
          # - beta
          # - dev

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      # - name: ESPHome ${{ matrix.esphome-version }}
      #   uses: esphome/build-action@v7
      #   with:
      #     yaml-file: ${{ matrix.file }}.yaml
      #     version: ${{ matrix.esphome-version }}
      - name: ESPHome ${{ matrix.esphome-version }} Factory
        uses: esphome/build-action@v7
        with:
          yaml-file: ${{ matrix.file }}.factory.yaml
          version: ${{ matrix.esphome-version }}
